name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
      - uses: actions/checkout@v4
      - name: Install Nodejs and npm
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependences
        run: npm ci
      - name: Run tests
        run: npm test
