name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "latest"
        cache: 'npm'
    - name: Create .env file
      run: echo "TEST_DB_URI=${{ secrets.TEST_DB_URI }}" > .env
    - run: npm ci
    - run: npm test
